#!/bin/sh

IP=10.0.1.1
PORT=5050
TIME=1

heartbeat_loop() {
  while true; do
    curl -X POST http://${IP}:${PORT}/heartbeat/`hostname` > /dev/null  2>&1  &
    sleep ${TIME}
  done
}

echo -n "Starting Heartbeat: "
heartbeat_loop &
echo "[OK]"
